import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACDSClfNYANTDuRQzDOiUcudeFwUWXzCa7uHyKbPO+PEKgAAAJAohnAsKIZw
LAAAAAtzc2gtZWQyNTUxOQAAACDSClfNYANTDuRQzDOiUcudeFwUWXzCa7uHyKbPO+PEKg
AAAEBCywn9bQaIwbUz/2t+xycW8XKvxzACbfdVyCee3jFTS9IKV81gA1MO5FDMM6JRy514
XBRZfMJru4fIps8748QqAAAABm15LWtleQECAwQFBgc=
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
